
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: unique_syms
    description: "Unique stock symbols from all gainers tables"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        data_tests:
          - unique
          - not_null
